lang: cpp
dist: xenial
compiler: gcc
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake-data
      - cmake
      - libsdl2-dev
      - bison

before_script:
  - sudo add-apt-repository ppa:rexut/recoil -y
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y
  - sudo apt-get update -
  - sudo apt-get install boost1.63
  - sudo apt install qt511-meta-full
  - mkdir -p ~/.config/qtchooser
  - echo /opt/qt511/bin > ~/.config/qtchooser/default.conf
  - echo /opt/qt511/lib >> ~/.config/qtchooser/default.conf


script:
  - qmake -v
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/  
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Executor*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

  - make
  - ctest . -LE xfail

